# Inherit fields from the unrolled.yaml config.
_BASE_: "../../templates/unrolled.yaml"
# DATALOADER has 14 supervised scan
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 14
    NUM_UNDERSAMPLED: 13
OUTPUT_DIR: results://vortex-rm/mridata_knee_3dfse/unrolled/vortex/vortex_multi_aug_unrolled_14_scan
DESCRIPTION:
  BRIEF: f"VORTEX Semi Supervised Multi Aug Noise Aug Unrolled 14 Scan {AUG_TRAIN.UNDERSAMPLE.ACCELERATIONS}x mridata - loss={MODEL.RECON_LOSS.NAME}"
  EXP_NAME: mridata_knee_3dfse/unrolled/vortex_semi_supervised_multi_aug_noise_aug_14_scan
  TAGS:
  - baseline
  - vortex 
  - semisupervised
  - 14_scan 
  - 16x
  - mridata_knee_3dfse
  - unrolled
  - noise_aug
# For no motion aug, A2R and Consistency was removed.
# For Unrolled, made META_ARCHITECTURE GeneralizedUnrolledCNN
MODEL:
  META_ARCHITECTURE: VortexModel 
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
  RECON_LOSS:
    NAME: k_l1
    RENORMALIZE_DATA: false
  A2R:
    META_ARCHITECTURE: GeneralizedUnrolledCNN 
  CONSISTENCY:
    AUG:
      MRI_RECON:
        TRANSFORMS: 
        - name: RandomMRIMultiShotMotion
          tfms_or_gens:
          - name: RandomAffine
            p: 1.0
            angle: 2 
            translate: 0.03
            scale: 1.0
            shear: 0 
          nshots: 2
          trajectory: blocked 
          p: 1.0
    LOSS_NAME: k_l1
VERSION: 1

