# Inherit fields from the unrolled.yaml config.
_BASE_: "../../templates/unrolled.yaml"
# DATALOADER has 14 supervised scan
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 14
    NUM_UNDERSAMPLED: 13
OUTPUT_DIR: results://vortex-rm/mridata_knee_3dfse/unrolled/vortex/vortex_multi_aug_noise_aug_unrolled_14_scan
DESCRIPTION:
  BRIEF: f"VORTEX Semi Supervised Multi Aug Unrolled 14 Scan {AUG_TRAIN.UNDERSAMPLE.ACCELERATIONS}x mridata - loss={MODEL.RECON_LOSS.NAME}"
  EXP_NAME: mridata_knee_3dfse/unrolled/vortex_semi_supervised_multi_aug_14_scan
  TAGS:
  - baseline
  - vortex 
  - semisupervised
  - 14_scan 
  - 16x
  - mridata_knee_3dfse
  - unrolled
# For no motion aug, A2R and Consistency was removed.
# For Unrolled, made META_ARCHITECTURE GeneralizedUnrolledCNN
MODEL:
  META_ARCHITECTURE: VortexModel 
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
  RECON_LOSS:
    NAME: k_l1
    RENORMALIZE_DATA: false
  A2R:
    META_ARCHITECTURE: GeneralizedUnrolledCNN 
  CONSISTENCY:
    AUG:
      MRI_RECON:
        TRANSFORMS: 
        - name: RandomMRIMultiShotMotion
          tfms_or_gens:
          - name: RandomAffine
            p: 1.0
            angle: 2 
            translate: 0.03
            scale: 1.0
            shear: 0 
          nshots: 2
          trajectory: blocked 
          p: 1.0
        - name: RandomNoise
          p: 1.0
          std_devs:
          - 0.5
          - 0.7
          use_mask: true
      NOISE:
        MASK:
          RHO: 1.0
        SCHEDULER:
          WARMUP_ITERS: 0
          WARMUP_METHOD: ''
        STD_DEV:
        - 1
    LOSS_NAME: k_l1
    LOSS_WEIGHT: 0.1
    NUM_LATENT_LAYERS: 1
    USE_CONSISTENCY: true
  CS:
    MAX_ITER: 200
    REGULARIZATION: 0.005
  DENOISING:
    META_ARCHITECTURE: GeneralizedUnrolledCNN
    NOISE:
      STD_DEV:
      - 1
      USE_FULLY_SAMPLED_TARGET: true
      USE_FULLY_SAMPLED_TARGET_EVAL: null
VERSION: 1

AUG_TRAIN:
  MOTION_P: 0.2
  MRI_RECON:
    AUG_SENSITIVITY_MAPS: true
    SCHEDULER_P:
      IGNORE: false
    TRANSFORMS: []
  NOISE_P: 0.2
  UNDERSAMPLE:
    ACCELERATIONS:
    - 8
    CALIBRATION_SIZE: 0
    CENTER_FRACTIONS:
    - 0.04
    MAX_ATTEMPTS: 30
    NAME: RandomMaskFunc1D
  USE_MOTION: false
  USE_NOISE: false
CUDNN_BENCHMARK: false
