_BASE_: "template.yaml"
AUG_TRAIN:
  MRI_RECON:
    AUG_SENSITIVITY_MAPS: true
    TRANSFORMS:
    - name: RandomMRIMultiShotMotion
      tfms_or_gens:
      - name: RandomAffine
        p: 1.0
        angle: 2
        translate: 0.03
        scale: 1.0
        shear: 0 
      nshots: 2
      trajectory: blocked 
      p: 1.0