_BASE_: "template.yaml"
AUG_TRAIN:
  MRI_RECON:
    AUG_SENSITIVITY_MAPS: true
    TRANSFORMS:
    - name: RandomMRIMultiShotMotion
      p: 0.2
      seq_tfm_gens:
      - name: RandomAffine
        p: 0.2
        angle: 10
        translate: 0.5
        scale: 0.2
        shear: 30
      - name: RandomAffine 
        p: 0.2
        angle: 0 
        translate: 0.5
        scale: 0.2
        shear: 30
      - name: RandomAffine 
        p: 0.2
        angle: 10 
        translate: 0
        scale: 0.2
        shear: 30